#!/bin/bash
dest="includes.tw2"
currentPost=${PWD##*/}
files=(*)

echo "::StoryIncludes" > $dest

for file in "${files[@]}"
do
 if [ $file != "includes.tw2" ]; then
    echo "posts/"$currentPost"/"$file >> $dest
 fi
done